version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    env_file:
      - .env
    depends_on:
      - server
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    volumes:
      - .:/server
      - /server/node_modules
    command: npm run dev:server
